### PR TITLE
fix things.search: escape query

### PR DESCRIPTION
**Pull request by mikez**

### CODE REVIEW

**Comment by AlexanderWillner** [comment]
Maybe a good opportunity to start using [parametrized  queries](https://www.btelligent.com/blog/best-practice-fuer-sql-statements-in-python/) instead?

**Comment by mikez** [comment]
@AlexanderWillner See the third note in the `escape_string` function. :)

**Comment by mikez** [comment]
Also, I would suggest to take articles stating "best practices" slightly less seriously. Software engineering is young, changing fast, and many philosophies exist. We really don't know what we're doing. I find it way more important to think from first principles.

**Comment by mikez** [comment]
Fixes #66

**Pull request merged**
