### PR TITLE
fix `things.database.make_filter`: escape value string

### PR DESCRIPTION
**Pull request by mikez**
This fixes a bug @AlexanderWillner discovered [here](https://github.com/thingsapi/things.py/pull/65/files#diff-58fc39d66dcaf4da63603de1f8d966d8aefcc65d5f5836b6969c14e34cdbc1beR247).

### CODE REVIEW

**Comment by AlexanderWillner** [comment]
reduced coverage to 87%

**Comment by mikez** [comment]
> reduced coverage to 87%

I think the coverage is the same it says so:
> Merging #69 (241c405) into main (6512320) will not change coverage.

This is still the old main branch before your wonderful additions.

**Comment by AlexanderWillner** [comment]
Ah, of course!

**Comment by AlexanderWillner** [comment]
you make it difficult for me to raise a `SystemExit` exception...

**Comment by mikez** [comment]
@AlexanderWillner :D

**Pull request merged**
