### PR TITLE
add checklists and tags in tasks; cleanup

### PR DESCRIPTION
**Pull request by mikez**

### CODE REVIEW

**Comment by mikez** [comment]
@AlexanderWillner how slow is the current `things.tasks` on your massive database? How slow is it when you pass in the `"include_items"` flag set to `True` for `things.areas`? — The current implementation does an SQL SELECT for every task with tags.

Also, I removed the "for other languages see here" part of the README, since currently there are not other languages there. Once that changes, I can add it back again. :)

**Comment by AlexanderWillner** [comment]
> @AlexanderWillner how slow is the current `things.tasks` on your massive database? How slow is it when you pass in the `"include_items"` flag set to `True` for `things.areas`? — The current implementation does an SQL SELECT for every task with tags.

With `include_items=True` everywhere: 
```shell
$ time make test
...
make test  0.40s user 0.18s system 98% cpu 0.589 total
```

Without `include_items=False` everywhere: 
```shell
$ time make test
...
make test  0.15s user 0.05s system 96% cpu 0.211 total
```

**Comment by mikez** [comment]
@AlexanderWillner Wow, and this is with your massive database, *not* the demo one? I'm amazed. Ok, maybe we don't have to optimize then at this time.

**Comment by AlexanderWillner** [comment]
Yes, this was with my private database. So my current assumption is that we don't have any scalability issue so far. With the demo database:

With `include_items=False` everywhere:
```shell
$ time make test
make test 0.18s user 0.05s system 96% cpu 0.238 total
```

With `include_items=true` everywhere:
```shell
$ time make test
make test  0.18s user 0.05s system 96% cpu 0.245 total
```

**Comment by mikez** [comment]
👍  This is great news. :)

**Pull request merged**
