### PR TITLE
Contribution Guidelines

### PR DESCRIPTION
**Pull request by chrisgurney**
Proposal for a set of contribution guidelines and instructions for things.py

### CODE REVIEW

**Comment by chrisgurney** [comment]
@mikez @AlexanderWillner Ready for review!

**Comment by mikez** [comment]
@chrisgurney Looks great to me! 🥳

@AlexanderWillner What do you think?

**Comment by AlexanderWillner** [comment]
> @AlexanderWillner What do you think?

Thanks a lot! Do you think we should add a warning to the section "Copy the test database to your Things app folder"? As this would overwrite your "production database" (i.e., your current database you're working with in Things.app)

**Comment by chrisgurney** [comment]
@AlexanderWillner
 
> Thanks a lot! Do you think we should add a warning to the section "Copy the test database to your Things app folder"? As this would overwrite your "production database" (i.e., your current database you're working with in Things.app)

Good idea. I've added a warning in step 2 to make sure they've actually done step 1. 😀
https://github.com/chrisgurney/things.py/blob/main/CONTRIBUTING.md

**Comment by AlexanderWillner** [comment]
Thanks, lgtm!

**Comment by mikez** [comment]
@chrisgurney I did some light editing for readability. Especially, I moved the instructions on how to edit the things database to the end, as in many cases this is not needed. Also, removed Windows-specific comments.

**Comment by chrisgurney** [comment]
@mikez Makes sense to me!

**Pull request merged**
