### PR TITLE
Fix all tests

### PR DESCRIPTION
**Pull request by AlexanderWillner**
@mikez probably ready to release after this one

### CODE REVIEW

**Comment by mikez** [comment]
Except for minor comment (brackets removed)... LGTM.

**Comment by AlexanderWillner** [comment]
> Except for minor comment (brackets removed)... LGTM.

Which brackets where?

**Comment by mikez** [comment]
> > Except for minor comment (brackets removed)... LGTM.
> 
> Which brackets where?

You fixed it in the last update. (Or the tool you used.)

**Review by mikez — CHANGES_REQUESTED** [review]
I forget you have to submit these things :D

**Pull request merged**
