### PR TITLE
Release v.0.0.3

### PR DESCRIPTION
**Pull request by mikez**

### CODE REVIEW

**Comment by AlexanderWillner** [comment]
Is the release just about changing `'` to `"`?

**Comment by mikez** [comment]
The release incorporates the changes I merged in after you launched v0.0.2. due --> deadlines. Etc. — Already uploaded it to pypi. :)

**Comment by AlexanderWillner** [comment]
(y)

**Comment by mikez** [comment]
@AlexanderWillner Today I learned, whatever tags I set on my branch will not be reflected in this branch. How do I set a tag and create a release on this things.py repo?

**Comment by AlexanderWillner** [comment]
By clicking on Release on the right side of this web site.

**Comment by mikez** [comment]
I don't seem to have that permission. Screenshot:

image

**Comment by AlexanderWillner** [comment]
Fixed - though I already gave you `owner` permissions, but I did not.

**Comment by mikez** [comment]
@mikez I've found no way to set tags; maybe this has to do with lack of permissions?

**Comment by mikez** [comment]
@AlexanderWillner I found no way to set tags; maybe this has to do with lack of permissions?

**Comment by AlexanderWillner** [comment]
mh, at least you should have all rights to do so:

image

**Comment by AlexanderWillner** [comment]
What happens when you open https://github.com/thingsapi/things.py/releases ?

**Comment by mikez** [comment]
✅  Works. Thanks.

**Pull request merged**
