### PR TITLE
Fix #117: add localtime to stop_date where clause

### LINKED ISSUE #117: timezone of completed tasks not taken into account
**To Reproduce**
I was looking for all tasks completed on 2024-02-25:

```
kwargs['status'] = None
kwargs['stop_date'] = f'{DATE}'
tasks = things.tasks(**kwargs)
```

...but it returns some tasks on the day before, particularly those that were completed close to midnight:

Here's the stopDate for one of the returned tasks: 1708826542.13277

> GMT: Sunday, February 25, 2024 2:02:22.132 AM
> Your time zone: Saturday, February 24, 2024 9:02:22.132 PM [GMT-05:00](https://www.epochconverter.com/timezones?q=1708826542.13277)

**Expected behavior**
When I supply a `stop_date` I expect it to be reflective of my local timezone: i.e., get all tasks completed on that day _for me_.

### PR DESCRIPTION
**Pull request by chrisgurney**
Fix for #117, by adding "localtime" to the `stop_date` where clause.

### CODE REVIEW

**Comment by AlexanderWillner** [comment]
Thanks for the PR, lgtm, not tested though (see comments in #117)

**Comment by chrisgurney** [comment]
Leaving a note for myself when I'm able to pick this up again:

Setting the TZ environment variable using `OS.environ` between invocations of the things.py API appears to work on a Mac, but not on a BSD system (or GitHub actions) per @mikez's test.

Next steps:

1. What is the way to change time zones mid script such that SQLite will notice the difference, and be able to query based on that?
2. After that's solved, how do I write a test for the  `.last` API call (to test the createdDate query change in this PR) that gets the right amount of tasks from a past date? (stashed my first attempt)

**Comment by chrisgurney** [comment]
Setting the TZ environment variable using `OS.environ` between invocations of the things.py API appears to work on macOS, but not on a BSD system (or GitHub actions) per @mikez's test.

*Next steps:*

1. What is the way to change time zones mid script such that SQLite will notice the difference, and be able to query based on that?
    - Try this: Call `time.tzset()` after changing the `TZ` variable per: https://docs.python.org/3/library/time.html#time.tzset
2. After that's solved, how do I write a test for the  `.last` API call (to test the createdDate query change in this PR) that gets the right amount of tasks from a past date? (stashed my first attempt)

**Comment by chrisgurney** [comment]
Forgot the other detail from my conversation with @mikez last week, which was that we think the call to `.last` only goes as far back as the _current time_ X days ago, rather than midnight of that day. 

So for example if I call the following...
`last_tasks = things.last(f"{days_ago}d", status="completed")`

...and it's currently 3:55pm, it only goes back `days_ago` days starting from 3:55pm on that day.

This means I can't create a reliable test that will cover the change I made to `make_unixtime_range_filter` to account for different timezones.

**Comment by chrisgurney** [comment]
Two thoughts here then:

1. Should we commit and try the test above as-is, or
2. Come to a decision on the behavior of `.last` and update its behavior, and _then_ complete this test so it covers both cases?

**Comment by mikez** [comment]
👍

I vote for splitting this into two PRs.

As for the behavior of "last", maybe @lmgibson can help us here as he was the architect here. In essence, the question is whether `last='2d'` should mean the last 48h from the time right now or the last two dates.

**Comment by chrisgurney** [comment]
@mikez Marked as _Ready for Review_ per your approval. 

@AlexanderWillner I believe this is over to you now (unless you disagree).

**Comment by mikez** [comment]
@chrisgurney I ran the tests. There seem to be some doctest failures still. You can run these with `make testdoc`.

**Comment by chrisgurney** [comment]
Hmm, I'm getting errors running `make testdoc`:
```
% make testdoc       
THINGSDB=tests/main.sqlite pytest --cov=things -W ignore::UserWarning --cov-report=xml --cov-context=test --doctest-modules
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov=things --cov-report=xml --cov-context=test
```

**Comment by chrisgurney** [comment]
@mikez Back to you.

**Comment by mikez** [comment]
@AlexanderWillner If you'd enjoy to do so, can you add a check for `pytest-cov` in the makefile; see https://github.com/thingsapi/things.py/pull/118#issuecomment-2189113454

**Comment by mikez** [comment]
@chrisgurney `make lint` and `make auto-style` may be helpful for the current failures.

**Comment by chrisgurney** [comment]
> @AlexanderWillner If you'd enjoy to do so, can you add a check for `pytest-cov` in the makefile; see [#118 (comment)](https://github.com/thingsapi/things.py/pull/118#issuecomment-2189113454)

Here's what I was thinking:
```
@type pytest >/dev/null 2>&1 || (echo "Run '$(PIP) install pytest; $(PIP) install pytest-cov' first." >&2 ; exit 1)
```

**Comment by mikez** [comment]
> > @AlexanderWillner If you'd enjoy to do so, can you add a check for `pytest-cov` in the makefile; see [#118 (comment)](https://github.com/thingsapi/things.py/pull/118#issuecomment-2189113454)
> 
> Here's what I was thinking:
> 
> ```
> @type pytest >/dev/null 2>&1 || (echo "Run '$(PIP) install pytest; $(PIP) install pytest-cov' first." >&2 ; exit 1)
> ```

You can do multiple arguments to pip: `pip install pytest pytest-cov`.

**Comment by chrisgurney** [comment]
@mikez Linting issues fixed. Thanks for the tips.

**Comment by mikez** [comment]
@chrisgurney 🥳🙌

**Comment by chrisgurney** [comment]
Everything passed!

I think it would also be helpful to add a [CONTRIBUTING](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file to the project that: 

1. suggests the `make` commands to run prior to submitting a PR, which for me was `test`, `testdoc`, and `lint`;
2. talks to how to copy over the test Things database (after backing up your own) via `make db-to-things` and `make db-from-things`, and a disclaimer about making changes to it (schema knowledge perhaps being a pre-requisite here);
3. @mikez helped me with was setting up a venv, which was new to me as a relatively new Python developer -- might be helpful to point to the docs for that;

**Comment by mikez** [comment]
@chrisgurney Good idea! Do you want to craft such a simple file?
You could model it on other CONTRIBUTING.md files that you enjoy.

**Comment by chrisgurney** [comment]
> @chrisgurney Good idea! Do you want to craft such a simple file? You could model it on other CONTRIBUTING.md files that you enjoy.

Thought you might suggest that. 😅 Perhaps when I come back to the second test, once (if) `.last` is updated.

**Comment by chrisgurney** [comment]
@mikez I've got a draft of CONTRIBUTING.md almost ready. I'll submit a PR soon.

**Pull request merged**
